name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v1

      - 
        name: Build 
        run: docker build -t opencv:local . 

      - 
        name: Run
        run: docker-compose run --rm sampling
