name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: /home/ec2-user/ffmpeg-video-sampling
          tags: opencv:local

      - 
        name: Check directory
        run: echo $(ls)

      - 
        name: Pull repository
        run: git pull 
          
      - 
        name: Run
        run: docker-compose run --rm -d -f /home/ec2-user/ffmpeg-video-sampling/docker-compose.yaml sampling
