name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:

      - 
        name: Checkout
        uses: actions/checkout@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: opencv:local
          
      - 
        name: Run
        run: docker-compose run --rm -d sampling
